#!/usr/bin/env bash
# Created by Alec Glisman (GitHub: @alec-glisman) on March 22nd, 2022
#

# built-in shell options
set -o errexit # exit when a command fails. Add || true to commands allowed to fail
set -o nounset # exit when script tries to use undeclared variables
# bash extended options
shopt -s extglob

# path variables
if [[ "${INPUT_DATA_DIR}" == '-1' ]]; then
    base_dir="${REPO_BASE_DIR}/data/${TAG}"
else
    base_dir="${INPUT_DATA_DIR}"
fi

input_dir="${base_dir}/2-md-equilibration"
output_dir="${base_dir}/3-md-${PRODUCTION_ENSEMBLE}"
mdp_filename="${PARAMETERS_DIR}/molecular-dynamics/${PRODUCTION_ENSEMBLE}_prod_1000ns.mdp"

if [[ "${PRODUCTION_ENSEMBLE}" == "nvt" ]]; then
    input_simulation_name="nvt_eqbm_final"
    input_dir="${input_dir}/3-nvt"

elif [[ "${PRODUCTION_ENSEMBLE}" == "npt" ]]; then
    input_simulation_name="npt_eqbm"
    input_dir="${input_dir}/2-npt"

else
    echo "ERROR: Unknown production ensemble: ${PRODUCTION_ENSEMBLE}"
    exit 1
fi

# make parent directory
mkdir -p "${output_dir}"
cd "${output_dir}" || exit

# log paths
log_filename="standard_out_and_error.log"
touch "${log_filename}"

# copy force field
cp -rpn "${base_dir}/1-system-preparation/${FORCE_FIELD_NAME}.ff" .

echo ""
echo "Starting production..."

# ANCHOR: Generate windows by varying the reaction coordinate
echo " - ${PRODUCTION_ENSEMBLE} molecular dynamics production"
{
    gmx_mdrun_pipeline "${GMX_EXE}" \
        "${input_simulation_name}" "${mdp_filename}" "${input_dir}" \
        "${PRODUCTION_ENSEMBLE}_prod" "${output_dir}" "1-md-${PRODUCTION_ENSEMBLE}" \
        "${TEMPERATURE_K}" "${PBC_ATOM_CHAIN_A}" "${PBC_ATOM_CHAIN_B}" \
        "0" "${CPU_THREADS}" "${PIN_OFFSET}" "${GPU_IDS}"
} >>"${log_filename}" 2>&1

# create completion file
echo " - Cleaning up"
{
    date_time=$(date +"%Y-%m-%d %T")
    complete_str="Simulation completed at ${date_time} on host ${HOSTNAME}"
    echo "${complete_str}" >>"${base_dir}/completed.txt"
} >>"${log_filename}" 2>&1
