name: md
channels:
  - defaults
  - intel
  - numba
  - bioconda
  - conda-forge
dependencies:
  - python
  - pip
  - conda
  - ipykernel
  - ipywidgets
  - sqlite
  - autopep8
  - pylint
  - pathlib
  - tqdm
  - tbb
  - dask
  - joblib
  - numba
  - sphinx
  - nbsphinx
  - matplotlib
  - seaborn
  - colorcet
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - mdtraj
  - mdanalysis
  - plumed
  - py-plumed
  - panedr
  - gromacswrapper
  - parmed
  - moviepy
  - ffmpeg
  - imagemagick
  - vmd
  - nglview
  - openbabel
  - ambertools
  - acpype
  - ansible
  - docker-py
  - ranger-fm
  - wakatime
  - neovim
  - pynvim
  - gpustat
  - pip:
      - molywood
      - sphinx_rtd_theme
      - neovim-remote
      - nvitop
